package ab.async.tester.domain.requests.team

import io.circe.{Decoder, Encoder}
import io.circe.generic.semiauto.{deriveDecoder, deriveEncoder}

/**
 * Request model for creating a team
 * Does not include id, createdAt, modifiedAt as these are generated by the system
 */
case class CreateTeamRequest(
  orgId: String,
  name: String
)

object CreateTeamRequest {
  implicit val encoder: Encoder[CreateTeamRequest] = deriveEncoder
  implicit val decoder: Decoder[CreateTeamRequest] = deriveDecoder
}

