package ab.async.tester.domain.requests.testsuite

import ab.async.tester.domain.testsuite.TestSuiteFlowConfig
import io.circe.{Decoder, Encoder}
import io.circe.generic.semiauto.{deriveDecoder, deriveEncoder}

/**
 * Request model for creating a test suite
 * Does not include id, createdAt, modifiedAt as these are generated by the system
 */
case class CreateTestSuiteRequest(
  name: String,
  description: Option[String] = None,
  creator: String,
  flows: List[TestSuiteFlowConfig],
  runUnordered: Boolean = false,
  enabled: Boolean = true,
  orgId: Option[String] = None,
  teamId: Option[String] = None
)

object CreateTestSuiteRequest {
  implicit val encoder: Encoder[CreateTestSuiteRequest] = deriveEncoder
  implicit val decoder: Decoder[CreateTestSuiteRequest] = deriveDecoder
}

