package ab.async.tester.domain.requests.organisation

import io.circe.{Decoder, Encoder}
import io.circe.generic.semiauto.{deriveDecoder, deriveEncoder}

/**
 * Request model for creating an organisation
 * Does not include id, createdAt, modifiedAt as these are generated by the system
 */
case class CreateOrganisationRequest(
  name: String
)

object CreateOrganisationRequest {
  implicit val encoder: Encoder[CreateOrganisationRequest] = deriveEncoder
  implicit val decoder: Decoder[CreateOrganisationRequest] = deriveDecoder
}

